// =============================================================================
// Demo seed data — Operational Capability Delivery
// =============================================================================
// FICTIONAL data only. No real organisations, programmes, or operational
// information is represented here. This prototype is not approved for use
// with real planning data.
// =============================================================================

import { AppDomainState, Person, WorkItem } from './types';
import { recomputeSchedule } from '../engine/scheduleEngine';
import { deepCopyTasks } from '../engine/dependencyEngine';

export function seedPeople(): Person[] {
  return [
    { id: 'P01', displayName: 'Sarah Mitchell', email: 'sarah.mitchell@example.com', source: 'local' },
    { id: 'P02', displayName: 'James Okafor', email: 'james.okafor@example.com', source: 'local' },
    { id: 'P03', displayName: 'Rebecca Tan', email: 'rebecca.tan@example.com', source: 'local' },
    { id: 'P04', displayName: 'David Chen', email: 'david.chen@example.com', source: 'local' },
    { id: 'P05', displayName: 'Emma Walsh', email: 'emma.walsh@example.com', source: 'local' },
  ];
}

function rawSeedTasks(): WorkItem[] {
  return [
    {
      id: 'T01',
      title: 'Requirements baseline approval',
      status: 'complete',
      startDate: '2026-04-13',
      endDate: '2026-04-17',
      durationDays: 5,
      isMilestone: false,
      locked: false,
      swimlane: 'Define',
      percentComplete: 100,
      parentId: null,
      isParent: false,
      assignees: ['P01', 'P02'],
      dependencies: [],
      constraint: null,
    },
    {
      id: 'T02',
      title: 'System design package',
      status: 'in_progress',
      startDate: '2026-04-18',
      endDate: '2026-04-27',
      durationDays: 10,
      isMilestone: false,
      locked: false,
      swimlane: 'Define',
      percentComplete: 40,
      parentId: null,
      isParent: false,
      assignees: ['P02'],
      dependencies: [{ taskId: 'T01', type: 'finish_to_start', lagDays: 0 }],
      constraint: null,
    },
    {
      id: 'T03',
      title: 'Procurement contract award',
      status: 'backlog',
      startDate: '2026-04-28',
      endDate: '2026-05-05',
      durationDays: 8,
      isMilestone: false,
      locked: false,
      swimlane: 'Procure',
      percentComplete: 0,
      parentId: null,
      isParent: false,
      assignees: ['P03'],
      dependencies: [{ taskId: 'T02', type: 'finish_to_start', lagDays: 0 }],
      constraint: null,
    },
    {
      id: 'T04',
      title: 'Site preparation works',
      status: 'backlog',
      startDate: '2026-04-28',
      endDate: '2026-05-05',
      durationDays: 8,
      isMilestone: false,
      locked: false,
      swimlane: 'Procure',
      percentComplete: 0,
      parentId: null,
      isParent: false,
      assignees: ['P04'],
      dependencies: [{ taskId: 'T02', type: 'finish_to_start', lagDays: 0 }],
      constraint: null,
    },
    {
      id: 'T05',
      title: 'Equipment delivery & inspection',
      status: 'backlog',
      startDate: '2026-05-06',
      endDate: '2026-05-20',
      durationDays: 15,
      isMilestone: false,
      locked: false,
      swimlane: 'Procure',
      percentComplete: 0,
      parentId: null,
      isParent: false,
      assignees: ['P03', 'P04'],
      dependencies: [{ taskId: 'T03', type: 'finish_to_start', lagDays: 0 }],
      constraint: null,
    },
    {
      id: 'T06',
      title: 'Installation',
      status: 'backlog',
      startDate: '2026-05-21',
      endDate: '2026-06-01',
      durationDays: 12,
      isMilestone: false,
      locked: false,
      swimlane: 'Deliver',
      percentComplete: 0,
      parentId: null,
      isParent: false,
      assignees: ['P04'],
      dependencies: [
        { taskId: 'T05', type: 'finish_to_start', lagDays: 0 },
        { taskId: 'T04', type: 'finish_to_start', lagDays: 0 },
      ],
      constraint: null,
    },
    {
      id: 'T07',
      title: 'Integration & acceptance testing',
      status: 'backlog',
      startDate: '2026-06-02',
      endDate: '2026-06-11',
      durationDays: 10,
      isMilestone: false,
      locked: false,
      swimlane: 'Deliver',
      percentComplete: 0,
      parentId: null,
      isParent: true,
      assignees: ['P05'],
      dependencies: [{ taskId: 'T06', type: 'finish_to_start', lagDays: 0 }],
      constraint: null,
    },
    {
      id: 'T07a',
      title: 'System integration tests',
      status: 'backlog',
      startDate: '2026-06-02',
      endDate: '2026-06-05',
      durationDays: 4,
      isMilestone: false,
      locked: false,
      swimlane: 'Deliver',
      percentComplete: 0,
      parentId: 'T07',
      isParent: false,
      assignees: ['P02', 'P05'],
      dependencies: [],
      constraint: null,
    },
    {
      id: 'T07b',
      title: 'Operator training',
      status: 'backlog',
      startDate: '2026-06-06',
      endDate: '2026-06-08',
      durationDays: 3,
      isMilestone: false,
      locked: false,
      swimlane: 'Deliver',
      percentComplete: 0,
      parentId: 'T07',
      isParent: false,
      assignees: ['P05'],
      dependencies: [{ taskId: 'T07a', type: 'finish_to_start', lagDays: 0 }],
      constraint: null,
    },
    {
      id: 'T07c',
      title: 'Acceptance test execution',
      status: 'backlog',
      startDate: '2026-06-09',
      endDate: '2026-06-11',
      durationDays: 3,
      isMilestone: false,
      locked: false,
      swimlane: 'Deliver',
      percentComplete: 0,
      parentId: 'T07',
      isParent: false,
      assignees: ['P05'],
      dependencies: [{ taskId: 'T07b', type: 'finish_to_start', lagDays: 0 }],
      constraint: null,
    },
    {
      id: 'T08',
      title: 'User acceptance trial',
      status: 'backlog',
      startDate: '2026-06-12',
      endDate: '2026-06-19',
      durationDays: 8,
      isMilestone: false,
      locked: false,
      swimlane: 'Assure',
      percentComplete: 0,
      parentId: null,
      isParent: false,
      assignees: ['P01', 'P05'],
      dependencies: [{ taskId: 'T07', type: 'finish_to_start', lagDays: 0 }],
      constraint: null,
    },
    {
      id: 'T09',
      title: 'Operational readiness review',
      status: 'backlog',
      startDate: '2026-06-20',
      endDate: '2026-06-22',
      durationDays: 3,
      isMilestone: false,
      locked: false,
      swimlane: 'Assure',
      percentComplete: 0,
      parentId: null,
      isParent: false,
      assignees: ['P01'],
      dependencies: [{ taskId: 'T08', type: 'finish_to_start', lagDays: 0 }],
      constraint: null,
    },
    {
      id: 'T10',
      title: 'Service commencement',
      status: 'backlog',
      startDate: '2026-06-24',
      endDate: '2026-06-24',
      durationDays: 0,
      isMilestone: true,
      locked: true,
      swimlane: 'Assure',
      percentComplete: 0,
      parentId: null,
      isParent: false,
      assignees: [],
      dependencies: [{ taskId: 'T09', type: 'finish_to_start', lagDays: 1 }],
      constraint: { type: 'must_finish_on', date: '2026-06-24', hard: true },
    },
  ];
}

export function seedTasks(): WorkItem[] {
  // Run the schedule engine on a fresh copy so derived fields (criticalPath, floatDays)
  // are populated before the app sees the tasks.
  return recomputeSchedule(deepCopyTasks(rawSeedTasks()));
}

export function createInitialDomainState(): AppDomainState {
  return {
    tasks: seedTasks(),
    columns: [
      { key: 'backlog', label: 'Backlog' },
      { key: 'in_progress', label: 'In Progress' },
      { key: 'complete', label: 'Complete' },
    ],
    swimlanes: [
      { key: 'Define', label: 'Define' },
      { key: 'Procure', label: 'Procure' },
      { key: 'Deliver', label: 'Deliver' },
      { key: 'Assure', label: 'Assure' },
    ],
    workingCalendar: {
      highlightWeekends: true,
      holidays: [],
    },
    people: seedPeople(),
    // RAID seed data added in Phase 5
    risks: [],
    raidActions: [],
  };
}
